name: normalize
version: 0.8.0-dev.0+2
homepage: https://github.com/gql-dart/ferry/tree/master/normalize
description: Normalization and denormalization of GraphQL responses in Dart
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: gql
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.4
  lints: ^2.0.0
